# Generated by Django 4.2.1 on 2023-05-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapi", "0002_rename_cities_task_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_id", models.IntegerField()),
                ("region_id", models.IntegerField()),
                ("name_ar", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50)),
                ("longitude", models.CharField(max_length=50)),
                ("latitude", models.CharField(max_length=50)),
            ],
            options={"db_table": "cities",},
        ),
        migrations.CreateModel(
            name="UserCoordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("longitude", models.CharField(max_length=50)),
                ("latitude", models.CharField(max_length=50)),
            ],
            options={"db_table": "user_coordinates",},
        ),
        migrations.DeleteModel(name="task_schema",),
    ]
